In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/processed/features_topic_modeling.csv')
df.head()

,GLOBALEVENTID,SQLDATE,Actor1Code,Actor1Name,Actor2Code,Actor2Name,EventCode,GoldsteinScale,QuadClass,NumMentions,AvgTone,SOURCEURL,lang,Topic_ID,Topic_Name,content
0,1248558842,2025-06-09,BEN,COTONOU,Unknown,Unknown,70,7.0,2,20,3.267974,https://english.news.cn/20250609/833e6be5b34f4...,en,-1,Bruit,Shore cleanup event held to mark World Oceans ...
1,1248561281,2025-06-09,NGA,BENIN CITY,Unknown,Unknown,173,-5.0,4,3,-3.353659,https://punchng.com/ndlea-intercepts-drugs-dis...,en,8,8_drug_ndlea_cannabis_ofoyeju,Lagos Airport Drug Seizure: NDLEA Intercepts C...
2,1248560915,2025-06-09,BEN,BENIN,NGA,BENIN CITY,173,-5.0,4,2,-3.353659,https://punchng.com/ndlea-intercepts-drugs-dis...,en,8,8_drug_ndlea_cannabis_ofoyeju,Lagos Airport Drug Seizure: NDLEA Intercepts C...
3,1248547619,2025-06-08,BEN,BENIN,Unknown,Unknown,42,1.9,1,10,-0.990099,https://fr.allafrica.com/stories/202506080145....,fr,0,0_bénin_politique_web_pays,Afrique: Découverte - Des parlementaires congo...
4,1248547711,2025-06-08,GOV,GOVERNMENT,Unknown,Unknown,43,2.8,1,10,-0.990099,https://fr.allafrica.com/stories/202506080145....,fr,0,0_bénin_politique_web_pays,Afrique: Découverte - Des parlementaires congo...

In [3]:
df[df['Topic_Name']=='0_police_command_edo_arrest'].head()

,GLOBALEVENTID,SQLDATE,Actor1Code,Actor1Name,Actor2Code,Actor2Name,EventCode,GoldsteinScale,QuadClass,NumMentions,AvgTone,SOURCEURL,lang,Topic_ID,Topic_Name,content
18,1285873207,2026-01-26,ELI,ACTOR,USA,NEW YORK,42,1.9,1,6,0.233918,https://madamenoire.com/1634352/djimon-hounsou...,en,0,0_police_command_edo_arrest,Djimon Hounsou’s Ex Shares Audio Of Fight Befo...
19,1285873770,2026-01-26,USAELI,UNITED STATES,USA,NEW YORK,42,1.9,1,2,0.233918,https://madamenoire.com/1634352/djimon-hounsou...,en,0,0_police_command_edo_arrest,Djimon Hounsou’s Ex Shares Audio Of Fight Befo...
26,1281832949,2026-01-02,CVL,CITIZEN,Unknown,Unknown,10,0.0,1,4,-7.848569,https://punchng.com/from-benin-to-ilorin-the-n...,en,0,0_police_command_edo_arrest,Jungle Justice in Nigeria: The Normalisation o...
27,1281832975,2026-01-02,CVL,CITIZEN,Unknown,Unknown,181,-9.0,4,4,-7.848569,https://punchng.com/from-benin-to-ilorin-the-n...,en,0,0_police_command_edo_arrest,Jungle Justice in Nigeria: The Normalisation o...
49,1281675550,2025-12-31,MIL,COMMANDANT,Unknown,Unknown,10,0.0,1,5,-9.577465,https://dailypost.ng/2025/12/31/nscdc-arrests-...,en,0,0_police_command_edo_arrest,NSCDC arrests suspected oil installation vanda...